### ISSUE TITLE
Usefulness of std::byte

### ISSUE THREAD

**Issue by MarcBrout** [kiwixz/sza#1]
Why use std::byte ?

Since HTTP is a text based protocol and in some rare cases raw data is transfered (as a body mostly) is it really useful ? Like specified in [this](https://stackoverflow.com/questions/46150738/how-to-use-new-stdbyte-type-in-places-where-old-style-unsigned-char-is-needed) post, it will force us to do some extra transformation to be able to parse correctly the requests.

Any encryption method works on chars directly too.

Since the documentation is not done yet, what are your reasons for using std::byte?

**Comment by butche-p** [comment]
```cpp
/**
* Type used to receive and send packets.
*/
using Raw = std::vector<std::byte>;
```

This is meant to store incoming packets from the sockets and there is no guarantee that the received data is always composed of chars. As explained in your quoted post's [answer](https://stackoverflow.com/a/46151026):
> The reason it was invented is to hold a raw byte in memory without the assumption that it's a character.

Which is exactly what we want, the network interface doesn't know what it's sending/receiving. It's up to the next modules down the line to read the data as they wish.

**Comment by MarcBrout** [comment]
And, I can also quote the post :
> Don't use bytes unless you want to store raw memory that should not be interpreted as char by default.

We're using HTTP, Hyper **Text** Transfer Protocol, we **know** we are receiving text almost all the time, and raw bodies in very rare cases. We are receiving `char` by default.

Using raw complicate things for almost everything, and a raw is basically an `unsigned char` with removed operators lol.

**Comment by scorsi** [comment]
I hope you didn't create `std::vector<std::byte>` just because `std::byte` is new in c++17 ([en.cppreference.com](http://en.cppreference.com/w/cpp/types/byte)).

I like this sentence about `std::byte` from the link above:
`Like char and unsigned char, it can be used to access raw memory occupied by other objects (object representation)`
That said that `std::byte` is quite similare to `char`. Interesting.
And if we look at `std::basic_string` ([en.cppreference.com](http://en.cppreference.com/w/cpp/string/basic_string)) we can see that `std::string` is an alias to `std::basic_string<char>`.

So in fact `std::string` is quite similare to `std::vector<char>` which is better than `std::vector<std::byte>` but with a lot of important and useful features in less.

But you can use `std::basic_char<unsigned char>` which will be better in that case.

**Comment by butche-p** [comment]
The use of `std::byte` here is to express the fact that we are receiving uninterpreted and possibly binary data directly read from sockets. The network interface should not make the assumption that all incoming/outgoing data are simple `std::char`.
`std::byte` is more than just a type on which you can or cannot perform certain operations, it's usage helps understand how much information we have on some data at a certain point in our program.

**Comment by scorsi** [comment]
So, you prefer to reduce the possibilities and thus allow people to understand better.
You take us for idiots?

I notice you that the attribute/parameter name is important to know what is comming. Type `raw_data` is **self-explanatory**.

In the worst case, you can use documentation.
For example, if you type:
```cpp
/**
 * This data comes directly from the socket, it may contains binary data
 *      which cannot be displayed.
 *      It first have to be translated (e.g. by the SSL module).
 */
std::basic_string<unsigned char> raw_data;
```
I think that everyone could understand that.

This is the first time I see people use a different type just to explain what is the uses of a variable.

**Comment by Stargateur** [comment]
I don't really understand what is the purpose of `Net` class, "Interface for multithreaded network abstraction.", If this is an abstraction why use primary type `byte` ? I don't understand how you use it to create a server, or handle client. An exemple of use would help a lot.

@MarcBrout HTTP2 is a binary protocol, https://en.wikipedia.org/wiki/HTTP/2

**Comment by scorsi** [comment]
Well... HTTP means "Hypertext Transfer Protocol" soooo Text Protocol.
And in the given link, it's absolutly never said that this is a binary protocol.
TCP and UDP are binary protocol but this is not the case of HTTP.

**Comment by Stargateur** [comment]
@scorsi Did you notice that I'm talking about HTTP2 and not HTTP ?

If you don't believe me, I invite you to read the [RFC 7540](https://tools.ietf.org/html/rfc7540#section-3.5), where It's clear that it's a binary protocol.

> The client connection preface starts with a sequence of 24 octets,
   which in hex notation is:
       `0x505249202a20485454502f322e300d0a0d0a534d0d0a0d0a`

Again, I was just saying, to do a complete server HTTP, handle HTTP2 is a plus and if you need to do this it's useful to know that HTTP2 is a binary protocol.

**Comment by scorsi** [comment]
Well, in fact Zia have to handle HTTP/1.1 not HTTP/2.

But there're indend some binary informations which are transfered. I will look at this more precisly tomorrow.

**Comment by scorsi** [comment]
Tell me if I'm wrong. If I understand, theses bits didn't take part of the HTTP Transfert but only for HTTP/2 Connection. Client and Server have to exchange some binary data to know if the other support HTTP/2. So binary data didn't take part of the HTTP Request / Response and have to be handle by the server only.

**Comment by eliastre100** [comment]
@Stargateur 
If I don't misunderstand the 7500 RFC

> 0x505249202a20485454502f322e300d0a0d0a534d0d0a0d0a

Can be in fact translates as ascii like this string:

> PRI *HTTP/2.0\r\n\r\nSM\r\n\r\n

> The client connection preface starts with a sequence of 24 octets,
> which in hex notation is:
> 
> 0x505249202a20485454502f322e300d0a0d0a534d0d0a0d0a
>
> That is, the connection preface starts with the string "PRI *
> HTTP/2.0\r\n\r\nSM\r\n\r\n").

It doesn't prove that it's a binary protocol. However, the frame format might have been a better example. (Even if I don't agree with keeping this std::byte buffer)

https://tools.ietf.org/html/rfc7540#section-4.1

**Comment by Stargateur** [comment]
@scorsi I don't know.
@eliastre100 You right, this wasn't a good exemple.

Note that I don't much about this API, I didn't understand anything. How you going to build any HTTP server based on this interface ? I don't know, I don't see any logic in this repository.

About `std::byte`, to know if it's better or not to keep it, first there should be some usable API. Here I just see some header file that don't make sense to me. I don't understand this conversation or other issues. Why talk about change one type when all the API don't make any sense.

Again, can we have a usable exemple about how to use this API in real scenario.

**Comment by kiwixz** [comment]
We use `std::byte` because **we don't know/care what data this is**, as the "raw" in the name and type suggest. It could, for example, be an HTTP message with a text or binary body, or maybe some random bytes.
The `std::byte` type was created exactly for this purpose: representing raw memory without the assumption that its only made of characters. It makes no sense to do some arithmetic operations on raw memory, or use any of the methods `std::string` would have over `std::vector`.

You are supposed to have a module to parse the request headers, from `raw_req` to `req` and another one to build the response headers from `resp` to `raw_resp`.

@Stargateur a question asking for more examples needs its own issue, and you will need to be more specific about what you do not understand.

**Comment by MarcBrout** [comment]
Then why not simply use something like suggested in this [post](https://www.yammer.com/epitech.eu/threads/1001876779?message_id=1004118979)

**Comment by PierreBougon** [comment]
If the goal of `std::byte` is only to give a coherant naming to understand that we're using Byte you should do this :

```cpp
using Byte = unsigned char; 
```

*so we would have :*

```cpp
basic_string<Byte>
```

*And raw could be that way :*

```cpp
using Raw = basic_string<Byte>;
```

You can keep useful char methods and keep a coherant naming.

**Comment by scorsi** [comment]
Or
```cpp
using Raw = std::vector<Byte>;
```
(but I prefere the usage of `std::string`/`std::basic_string`)

**Comment by Stargateur** [comment]
@PierreBougon @scorsi To defend the choice of `std::vector<std::byte>`, there is a big difference with `std::basic_string<unsigned char>`. One with be a string, the other is not. There is a lot of legacy thing in C++, `std::string` is one of these.

You can't use `std::basic_string` as stockage, one exemple is imagine you want use basic `read` POSIX function with your socket. It's impossible to use `read` into `std::string_basic` without overhead, indeed you need to use intermediate variable to after copy it's content into a `std::basic_string`. Plus, string for legacy reason are always null terminated, this will be impossible to use binary data with nul byte. Because the nul byte will be interpret as the end of your string. For all these reason you can't modify the `char const *` return by [`c_str()`](http://en.cppreference.com/w/cpp/string/basic_string/c_str). **So you can't use `std::basic_string` for binary data.**

With `std::vector` you can very easily do all there things:

```
std::vector<std::byte> bytes;
// ...
bytes.resize(n);
ssize_t ret = read(fd, bytes.data(), n);
if (ret == -1) {
  return 1;
}
bytes.resize(static_cast<container::size_type>(ret));
```

So if the purpose of the API is to read binary data, `std::vector<std::byte>` is a very choice.

Note: One of the big difference is that `std::byte` it is not a character type, this allow compiler to do crazy optimization cause character type are allow to alias other type, if you want to know more about that read [this](https://blog.regehr.org/archives/1307).

**Comment by PierreBougon** [comment]
You can use basic_string as a vector with iterators it won't be null terminated, and you can use it as a string to basically parse it or print it or whatever you could possibly do in a text protocol.

**Comment by Stargateur** [comment]
@PierreBougon "You can use basic_string as a vector with iterators it won't be null terminated", I think you didn't understand the problem of insert a nul byte in the middle of a string.

**Comment by scorsi** [comment]
@PierreBougon, well I have to recognize that @Stargateur is right.
If your string is `aze\0toto` it "become" `aze`.

I didn't try it, but this seems absolutly logic.

**Comment by PierreBougon** [comment]
@scorsi It's not true since string is NOT null terminated, well I will give you an example :

```cpp
#include <iostream>
#include <string>

int main()
{
    std::basic_string<char> str("aze\0toto", 8);

    for (auto it = str.begin(); it != str.end(); ++it)
    {
        std::cout << *it << std::endl;
    }
    return 0;
}
```
Try it and you will understand that it is not that logic.

**Comment by Stargateur** [comment]
@PierreBougon Of course, it's possible, you are in C++, the language trust the user. That said, your code will not be optimize and your string could be used as C-string.

> In C++ it's harder to shoot yourself in the foot, but when you do, you blow off your whole leg.
> Bjarne Stroustrup.

`std::string` and similar are not suitable to stock byte. They design to handle string, if you can't understand that, you don't understand object.

**Comment by scorsi** [comment]
Yeah, in fact I made some test too.

```cpp
std::basic_string<unsigned char> str;
    for (const unsigned char c : "test;tata;titi\0test;tutu") {
        str.push_back(c);
    }

    std::cout << str.length() << std::endl;

    int counter = 0;
    for (const auto &i: str) {
        ++counter;
    }

    std::cout << counter << std::endl;
```
Which gave:
```
25
25
```
And if you display it, you obtain:
```
test;tata;titi test;tutu
```

**Comment by kiwixz** [comment]
Let me reformulate:
- Why should we change container to `std::string` ?
- Why should we change type to `unsigned char` ? (do not tell me it is to allow arithmetic operations, because we specifically do **NOT** want them)

**Comment by MarcBrout** [comment]
* Changing to std:: string wasn't in the initial issue.  
* My concerns were mainly about having to cast every byte to char to rebuild the headers and the txt bodies. 
But since we're using vectors, we will be forced to build strings char by char. So adding a cast shouldn't affect the "efficiency" more than that. 
I understand your decisions about using std::byte on the theoric part, but I'm not it's that practical and efficient.

**Comment by scorsi** [comment]
The main raison for me is the potential response from module. They all should translate to fit in the actual container. PHPCGI returns string, PNG is string and so on...

**Comment by kiwixz** [comment]
@MarcBrout If you have figures measuring loss of performance that would justify losing clarity in the code, please provide them.

**Comment by scorsi** [comment]
@kiwixz. As I said, modules uses string. So how can I fill the `std::vector<std::byte>` ?
I tried:
```cpp
http.resp.body = "test";
http.resp.body = {0x122, 0x123, 0x124, 0x125};
```
This is the only working usage I found for writing a string into the `std::vector<std::byte>`, I guess we can see here the loss of preformances:
```cpp
http.resp.body.clear();
for (const auto &item: "test") {
    http.resp.body.push_back(std::byte{static_cast<std::byte>(item)});
}
```

**Comment by kiwixz** [comment]
@scorsi Actual figures would be greatly appreciated.

What about ?
```cpp
#include <cstddef>
#include <vector>
#include <string>
#include <algorithm>

int main()
{
    std::string from = "hello";
    std::vector<std::byte> to;

    std::transform(from.begin(), from.end(), to.begin(), [](char c){ return static_cast<std::byte>(c); });
}
```

**Comment by scorsi** [comment]
I run the exact sample and I got a SIGSEV...
In the transform, it seems that the vector cannot extends by its own. I got "Cannot access memory at address 0x0". We have to `reserve` memory to the vector. But this sample after the edit didn't work.
I have the following code:
```cpp
std::string from = "hello";
std::vector<std::byte> to;

to.reserve(from.length() + 1);

std::transform(from.begin(), from.end(), to.begin(), [](char c){ return static_cast<std::byte>(c); });

for (const auto &item: to) {
    std::cout << static_cast<char>(item);
}
```
The `std::cout` display nothing.

**Comment by Stargateur** [comment]
``` C++
#include <iostream>
#include <vector>
#include <string>
#include <cstddef>
#include <algorithm>
#include <iterator>

int main()
{
    std::string from = "hello";

    std::vector<std::byte> to;
    std::transform(from.begin(), from.end(), std::back_inserter(to), [](char c){ return static_cast<std::byte>(c); });
    
    for (auto item: to) {
        std::cout << static_cast<char>(item);
    }
}
```
