### ISSUE TITLE
Doc?

### ISSUE THREAD

**Issue by scorsi** [kiwixz/sza#11]
Can we have full documented header files and doxygen ?
Do you realize that the doxygen hasn't its title configured.

**Comment by kiwixz** [comment]
What part of the codebase dont you understand ?

**Comment by scorsi** [comment]
Everything

**Comment by kiwixz** [comment]
That is really problematic. If even the doxygen does not help you, we unfortunately can not do anything for you unless you are more specific.
Your local assistants may be able to help you.

**Comment by scorsi** [comment]
Can you please comment and document each fields on headers to allow us understand everything ? :/

Saying that a HttpResponse is a Response cannot be considered as correct documentation. Could you please comment each fields especially for Net::Raw in HttpDuplex, HttpResponse and HttpRequest.

Plus, the doxygen isn't enough and seems incomplete.

**Comment by PierreBougon** [comment]
Please the code of the API must be documented, we've guessed most of the code and this is a source of misunderstanding. If you want some useful feedback and if you want your API to be usable you should document it.

**Comment by kiwixz** [comment]
The "undocumented" code should be self-explanatory. I'm sure every field you fail to fully understand are explained more thoroughly in issues.

**Comment by scorsi** [comment]
So, after the "Your local assistants may be able to help you." we got "I'm sure every field you fail to fully understand are explained more thoroughly in issues.".
Please, say us if you don't want to make your job.

So I guess, this issue is closed like every one in this repos ?

**Comment by kiwixz** [comment]
I can't explain to you every bit of C++, it is not my job. You should do some researches before asking questions, of C++ but also of already discussed code.

**Comment by scorsi** [comment]
I think I can say that I know all the issues as I participate in all.

**Comment by scorsi** [comment]
So you don't want to make more docs ?

**Comment by kiwixz** [comment]
Unfortunately we can **NOT** help you until you are more specific.
