### ISSUE TITLE
Exemple, doc, etc..

### ISSUE THREAD

**Issue by ArnaudWurmel** [kiwixz/sza#12]
Hello,

Comment devons-nous faire pour permettre au module NET d'être détecté en tant que tel ? J'ai bien compris que la fonction create() retourne un NET* dans ce cas là à la place d'un Module* mais du coup faut-il essayer tout les fichiers .so du module_dir ? Est-ce défini dans la configuration ?
Et, est-il possible d'avoir un exemple de fichier de conf que vous avez ? (Si vous en avez un).

Bonne soirée !

**Comment by kiwixz** [comment]
Bonjour, comme répondu dans #9, c'est en effet défini dans la configuration.

Voici un example:
```json
{
    "port": 80,
    "port_ssl": 443,
    "module_net": "network_with_ssh",
    "modules": ["cgibin", "gzip", "logger"],
    "modules_path": [".", "modules"]
}
```

Le sujet ne semble pas requérir interopérabilité des fichiers de configurations, donc il semblerait que chacun est libre de définir sa structure.
