### ISSUE TITLE
How to specifie module order ?

### ISSUE THREAD

**Issue by scorsi** [kiwixz/sza#13]
Hi,

If I want to run my SSL Module before BasicAuthenticationModule before PHPCGI before ZIPModule before SSL Module, how can I do that ?

**Comment by kiwixz** [comment]
The modules will be executed in the order defined in the config, as documented in [conf.h](https://github.com/kiwixz/sza/blob/master/api/conf.h).

**Comment by scorsi** [comment]
"As documented" ? `"modules": a list of modules name e.g. "cgibin", "gzip", "logger" (extension will be appended, will be prefixed by "lib" on linux)`.
Yeah, there is a list of module. Is it said that the order of that list influence the execution order ? No. You should add it in your documentation.

**Comment by kiwixz** [comment]
As said in #12, AFAIK you're free to have your own configuration semantic.
