### ISSUE TITLE
Netword module

### ISSUE THREAD

**Issue by scorsi** [kiwixz/sza#14]
Ok as partially mentionned in #8.
- What is the "Network Module", what should it do ?
- Do it have to be included in the module pipeline / module exec list ?
- Where should I put my SLL Module ? In that module ?

**Comment by marinij** [comment]
All your questions are answered in #8.

**Comment by scorsi** [comment]
If I open this issue referencing #8 it's because I don't found sufficient answers in #8...

**Comment by scorsi** [comment]
What should do the Network Module exactly ?
It reads from socket the request ? It write on socket the response ?
If yes for both, it is executed 2 times so ? At the beginning and at the end ?

The Network Module is in the pipeline, right ?
Following your config file given in #12, the module must be registrated as "module_net", it so have to be executed first in the pipeline ?

The SLL Module must be a part of the Network Module or not ? You said yes but @kiwixz seems to not be agreed. Following the subject, the SSL Module must be apart of every thing.

**Comment by kiwixz** [comment]
The network module listen, reads and writes. It is not part of "the pipeline" because it actually triggers the callback who is launching "the pipeline".
As we said multiple times already, the Network module should integrate SSL, the Network module **IS** also the SSL module.

**Comment by scorsi** [comment]
So the `Network module` must listen, read and right on a socket. Ok.
When we talk about `Network module`, actually we talks about the `Net` class, right ?

How should it know which socket to listen from ? I mean, if it implements all of the network part of the ZIA, it should so detect new sockets connecting to the server ?
But when I see on the `Net` class we have a `run` method which give a `Callback` as parameter, so a `NetInfo` (which contains the `ImplSocket`). If the `Net` class should listen, read and right from a `ImplSocket`, it so have to call itself with the `run` method ? Why giving the `ImplSocket` to modules if they can't use it ? Because `Net` is apart from modules.

If the `Net` class must start the pipeline, how should it know which modules to execute ?

**Comment by PierreBougon** [comment]
Network can't be the SSL module since network is not in the pipeline and the SSL module have to be in the pipeline ...

**Comment by kiwixz** [comment]
@PierreBougon why would it have to be part of the pipeline ?

**Comment by PierreBougon** [comment]
Because it is the subject

**Comment by scorsi** [comment]
Yeah, I already said that... "Following the subject, the SSL Module must be apart of everything."

**Comment by kiwixz** [comment]
Please quote the exact wording of the subject.

**Comment by scorsi** [comment]
You can go check by yourself in "Modules" part.

Here's a screenshot:
![image](https://user-images.githubusercontent.com/8389441/34415385-b8bde59e-ebee-11e7-8f76-6d600137a498.png)

**Comment by kiwixz** [comment]
I see no indication impliciting that the SSL module must be apart of everything, or part of any pipeline, it just needs to be a module.

**Comment by scorsi** [comment]
Wow. OK I surrender..
