### ISSUE TITLE
Définition d'un "module" - Respect du sujet

### ISSUE THREAD

**Issue by Patazerty** [kiwixz/sza#16]
Après avoir lu les issues #8 et #14 je pense qu'il y a un malentendu par rapport à la définition même d'un module. Ce qui est appelé "network module" dans les deux issues **n'est pas** un module car il n'implémente pas module.h et fait donc partie du "core" du zia, il en va de même pour le "module ssl" qui d'après #14 devrait être partie intégrante du "network module" et donc du core.
Si l'on veut respecter le sujet et remplir ses conditions pour obtenir une note correcte, il faut changer cela et permettre aux modules (les vrais modules interchangeables, pas le core) d'accéder au socket pour échanger avec le client (principalement pour l'HTTPS). 
Une interface telle que proposée dans #8 par @scorsi accessible dans les modules me semble être une solution tout à fait honnête. Qu'en pensez-vous ?

**Comment by scorsi** [comment]
Je suis heureux de voir que mes commentaires sont lues. Merci de remonter ça de nouveau, peut-être que si c'est une personne différente, ils réagiront. Bon courage.

**Comment by kiwixz** [comment]
Votre définition de module est relative à la classe Module, alors que nous considérons "module" toute bibliothèque chargée dynamiquement (donc ceux qui composent la pipeline, mais aussi le network module).

**Comment by Patazerty** [comment]
Je pense qu'un module est différent du core du projet de part son aspect optionnel. La définition de module par le sujet laisse certes le choix de l'interprétation, cependant avoir un module qui est obligatoire pour que le serveur se lance perds à mon sens tout l'interêt d'être un module, surtout si ce module obligatoire est en réalité deux modules (network et https). Autant intégrer le réseau au core du zia ou au moins laisser le module HTTPS être séparé du module réseau. 
Certes la vision module = .so n'est pas nécéssairement incompatible avec le sujet selon l'interprétation, mais c'est selon moi tiré par les cheveux. Obliger à implémenter le module HTTPS avec le module réseau ne correspond pas aux principes énoncés de cette API ! "The point of this API is to restrict in no way your conception or design choices".

**Comment by kiwixz** [comment]
Si on veut profiter des sockets boost, il faut que la gestion du Network soit dans un module. Il nous semblé plus simple de nous organiser ainsi avec le module SSL. Un autre attrait d'un système modulaire est de changer certaine partie sans que ça en affecte d'autre, ici: changer de module Network (ou y ajouter des fonctionnalités) sans que ça change quoi que ce soit au niveau du core.

**Comment by Patazerty** [comment]
Je ne suis pas nécéssairement contre un module réseau, même si je trouve que cela donne un core qui est une coquille (très) vide, mais pourquoi pas. En revanche, distinguer module réseau et module HTTPS reste primordial, surtout qu'il suffit de changer ImplSocket par une interface (même très abstraite) pour que les modules puissent y accéder.

**Comment by Patazerty** [comment]
Des nouvelles ?

**Comment by kiwixz** [comment]
Le core n'est pas vide, il s'occupe par exemple du chargement de config et modules ainsi que du prompt qui va avec. L'API à été design de façon à ce que le module "réseau" fasse ce qu'il veut, il pourrait par exemple lire les requêtes d'un fichier et imprimer les réponses. Je t'invite à lire les autres issues pour plus de détails.
