### ISSUE TITLE
Séparation des modules réseau et https

### ISSUE THREAD

**Issue by Patazerty** [kiwixz/sza#17]
Bonjour !

Suite à l'issue #16 qui a été close, je réitère ma demande de séparation du module réseau et https. Si j'ai loupé un truc et qu'il y a un quelconque désavantage à cette séparation n'hésitez pas à m'en faire part.

**Comment by Patazerty** [comment]
Ping

**Comment by butche-p** [comment]
Comme expliqué dans l'issue #16:
 >Si on veut profiter des sockets boost, il faut que la gestion du Network soit dans un module.
Le socket n'est accessible que par le module Network, le module HTTPS ayant besoin d'accès au socket il fait donc parti du module Network.

**Comment by Patazerty** [comment]
Le problème est bien là: `Le socket n'est accessible que par le module Network`, en changeant ImplSocket par une interface très abstraite on peut séparer les modules réseau et https car le module https aurait accès au socket via cette interface

**Comment by polosskevin** [comment]
Et juste par pure curiosité votre supposé module network fait quoi ?

**Comment by kiwixz** [comment]
Cf. #19

**Comment by Patazerty** [comment]
L'issue n'a aucun rapport avec Boost: autorisé ou pas séparer les modules réseau et https reste le sujet de ma demande

**Comment by kiwixz** [comment]
Effectivement, la vraie question de cette issue a en revanche été répondue ailleurs: c'est un choix de conception que nous avons pris afin de simplifier l'API et surtout permettre au module "Network" d'être totalement libre.

**Comment by Patazerty** [comment]
Le prix à payer de cette liberté est d'enfermer le module https au module réseau. Il me sera donc impossible d'utiliser le superbe module réseau du groupe X avec l'excellent module HTTPS qui gère des ciphers exotiques du groupe Y. De plus, en quoi une interface très abstraite rend le module moins "libre" ?
