### ISSUE TITLE
dynamic loading

### ISSUE THREAD

**Issue by polosskevin** [kiwixz/sza#18]
It is not specify what is the symbol name for releasing a module ...      
* Dynamic libraries of modules must export a "create" C function returning a "Module*" (caller should use smart pointers).

**Comment by kiwixz** [comment]
You should of course use delete.

**Comment by polosskevin** [comment]
You can't delete a pointer that has been allocated with dynamic loading.

**Comment by kiwixz** [comment]
You indeed can. That's the whole point of virtual methods (like the destructor of the Module interface): the instance will contain a pointer to a virtual table thus allowing to call member functions of child class, and of course the destructor.
[You can read more here.](http://en.cppreference.com/w/cpp/language/virtual)

**Comment by polosskevin** [comment]
You missed the point. I'm talking about memory allocated with dynamic symbol. [You can read more here](https://en.wikipedia.org/wiki/Dynamic_loading).

**Comment by kiwixz** [comment]
Could you please elaborate with an example ?

**Comment by polosskevin** [comment]
Modules are supposed to be dynamically loaded, by this mean you're supposed to use the dynamic loading api. Your api ask to provide the symbol to create the module.
```c++
Module *m = create();
```
But you can't do:
```c++
delete(m);
```
It's mainly due to the fact that the dynamic library and your executable don't share the same memory.
In conclusion to avoid memory leak, you're supposed to have a constructor symbol and a destructor symbol to ensure that delete is being called by the dynamic library.

```c++
//define by the dynamic library:
extern "C" Module *create() {return new SomeModule();}
extern "C" void destroy(Module *m) {delete(m);}
//caller  space
Module *m = create();
destroy(m);
```

**Comment by kiwixz** [comment]
I did understand your question the first time, please read again my answer and the link I gave.

**Comment by polosskevin** [comment]
My answer is a short version but imagine this scenario:
```c++
//dll
SomeModule m;
Module *create() {
 return &m
}
```
```c++
//or for my network implementation in case i want my server to be only instantiate once.
Module *create() {
 static SomeModule m;
  return &m;
}
```
calling delete will definitely go wrong.

You can refer to the different best practices and implementation of dynamic loader in c++. Here are some lectures: https://stackoverflow.com/questions/40109135/c-dynamic-loading-of-classes-why-is-a-destroy-function-needed.

**Comment by kiwixz** [comment]
create is intended to create an object, not just return a reference to an existing one; so your code snippets are invalid. If you want to implement a singleton, it's your duty to do it right.
As said in the link you provided, the only reason to add a destroy function would be in case of new/delete overloading ?

**Comment by polosskevin** [comment]
One of the reason, you can also have different memory space, you could use a specific heap that delete doesn't manage. You could also init things in the create function that needs to be destroyed in another location than the class returned.

**Comment by kiwixz** [comment]
What do you mean by: a different memory space/a heap that delete doesnt manage ?
You should not do anything in the create function else than: `return new ModuleImpl();`.

**Comment by polosskevin** [comment]
All your justifications are not in your api:
- You should not do anything in the create function else than: return new ModuleImpl();
- create is intended to create an object, not just return a reference to an existing one; so your code snippets are invalid. If you want to implement a singleton, it's your duty to do it right.
Imagine that i use a module that doesn't use new ? because i'm using a library that manage its own memory ?

Implementing a singleton, this way is a good way. I only expose the same instance and its being instantiated only once.

By a different memory space, you could take as example the httpd from apache where they manage their own memory pool.

**Comment by polosskevin** [comment]
In addition delegating the delete of an object to the callee provide strong resilience as you're not making assumption of its implementation.

**Comment by kiwixz** [comment]
I dont understand what keeps you from abstracting the library you use (or any code) into a new class forwarding ctor, dtor and all functions call to anything you want ?
You did not implement a proper singleton (with his own delete mechanism), but that's besides the point anyway.

**Comment by polosskevin** [comment]
As i said all the argument that you're giving are not in the api, further more it oblige **implicitly which is terribly bad for an api** a certain implementation, that can be forgotten if you just provide a simple destroy symbol, which btw is the only correct way to implement dynamic loading of class in c++.

**Comment by kiwixz** [comment]
**No, this is not the correct way.** This is the C way.
C++ was made to solve this problem: you no longer need to manually free/delete/destroy anything. This is an essential part of the RAII principle and the same reason why we use smart pointers !

You should not trust any answer on StackOverflow without thinking by yourself and especially understanding what is said.

**Comment by polosskevin** [comment]
Why do you even site RAII and smart pointers while i'm talking about providing a symbol that avoid misbehaviour on dynamic object ?

I will forgot your last sentence as it clearly shows your lack of the subject.
