### ISSUE TITLE
Boost not authorized

### ISSUE THREAD

**Issue by MrBananane** [kiwixz/sza#19]
Citiation du sujet :
> Boost is forbidden in the server core but authorized in request processing modules

J'ai lu dans vos commentaires que vous suggérez l'utilisation de Boost dans l'implémentation de la classe `Net`. Or je n'ai pas l'impression du tout que le "module" implémentant `Net` soit un **request processing module** vu qu'il ne manie pas une requete mais juste de la data pure.
D'après mon interprétation du sujet, Boost n'est donc pas authorisée dans la class `Net`, même si celle-ci est chargée depuis une dll.

**Comment by kiwixz** [comment]
Une requête, peut importe sa forme, est une requête. Nous considérons donc requête ce que transmet le module implémentant Net, car il est à la fois le début et la fin de la phase "request processing".

**Comment by MrBananane** [comment]
On inerprète le sujet à notre avantage, mais okay.
Merci !
