### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by fraiss-c** [kiwixz/sza#20]
Why Module is a class an not an interface ?

**Comment by fraiss-c** [comment]
Why did you use a class instead of an interface ? Because your class acts as an interface so why you use class Module instead of interface IModule ?

**Comment by kiwixz** [comment]
Oh, is this issue about the name ?

**Comment by fraiss-c** [comment]
No `class Module` isn't the same as `interface IModule`

**Comment by kiwixz** [comment]
There is no such keywords in C++.
[More details here](http://en.cppreference.com/book/intro/abstract_classes)
