### ISSUE TITLE
Keep-Alive

### ISSUE THREAD

**Issue by MickaToast** [kiwixz/sza#21]
Bonjour,

Vu que l'API se base sur une création / destruction de socket dans le module Network, est-t'il possible de gérer le header Keep-Alive, et si tel est le cas, pourriez-vous détailler à l'aide d'un exemple de comment procéder?

Cordialement,

**Comment by kiwixz** [comment]
Les connections HTTP/1.1 sont implicitement persistantes, et il est effectivement possible de les gérer assez facilement. Par sa nature permissive, l'API ne vous impose pas de façon précise.
Vous pouvez par exemple garder une liste des connexions ouvertes (ImplSocket) et en passer un pointeur lors d'un requête.
