### ISSUE TITLE
Question : exemple de la documentation

### ISSUE THREAD

**Issue by Milerius** [kiwixz/sza#22]
Bonjour,

Petite question sur un exemple provenant de votre documentation : 
```cpp
moduleReceive.config(conf);
moduleTreatRequest.config(conf);
moduleSend.config(conf);
for each request :
	HttpDuplex http;
	moduleReceive.exec(http);
	moduleTreatRequest.exec(http);
	moduleSend.exec(http);
```
Comme on le voit ici, vous utilisez un module `moduleSend`, qui je suppose est responsable de l'envoi de la réponse. Il devrait donc utiliser le `ImplSocket` contenu dans le `NetInfo` de `http`, afin de pouvoir envoyer les données. Seulement, `ImplSocket` n'est pas défini (hormis, je présume, par le module `Net`), comment peut-on alors le manipuler ?

Je pensais pouvoir utiliser la méthode `Net::send`, seulement je ne vois aucun moyen de fournir une instance de `Net` à `moduleSend`. Pouvez-vous m'éclairer à ce sujet ?

Merci d'avance !

**Comment by Ralender** [comment]
je pense que "modulesend.exec(http)" n'est pas sencé envoyer la reponse mais just ecrire dans le httpduplex quoi repondre et on doit envoyé la reponse apres via Net::send

**Comment by kiwixz** [comment]
En effet, c'est le core qui envoie le message après la pipeline.

**Comment by Ralender** [comment]
se serai bien de repondre aussi au autre issue comme #25
