### ISSUE TITLE
Utilitée de Conf

### ISSUE THREAD

**Issue by MickaToast** [kiwixz/sza#23]
Bonjour,

Vu que la structure de configuration est définie par le server, a-t'elle vraiment une utilitée pour les modules?
Le module du groupe B ne sait pas comment sera configuré la configuration du server A, ce qui rend donc cette structure inutile.

Cordialement,

**Comment by kiwixz** [comment]
Une partie sera inutile, mais tout donner permet au module de choisir lui-même quelle valeur lire/définir.

**Comment by MickaToast** [comment]
Ces valeurs à lire ne sont pas forcément spécifiées par le serveur justement, idem pour les valeurs à définir, la suite des modules n'iront pas forcement lire ces données. Pourriez vous nous expliquer du coup "l'autre partie" utile? Car je ne la vois pas spécialement.

**Comment by kiwixz** [comment]
Je veux dire par là que vous pourriez par exemple rajouter `zlib.compression = 9` dans la configuration du serveur afin de configurer votre module gzip.

**Comment by MickaToast** [comment]
D'accord, les modules doivent avoir une configuration par défaut dans ce cas, car rien n'assure que le serveur définisse cette valeur ou la définisse correctement pour ce module.

**Comment by kiwixz** [comment]
Exact.

**Comment by Patazerty** [comment]
Personnellement, vu que l'implémentation est libre, j'ai séparé la conf globale et celle de chaque module. Dans la conf globale il est nécessaire de set les modules et le chemin vers le dossier qui contient les confs de chaque module, comme ça chaque module a sa propre configuration et il n'y a pas de problème d'incompatibilité si deux modules ont le même champ à configurer (même si cela est très improbable).
