### ISSUE TITLE
callback de net

### ISSUE THREAD

**Issue by Ralender** [kiwixz/sza#25]
quand est'on sencé apeller le callback du module net ?
je trouve qu'il y a des contradictions dans votre api a ce propos
si un envoie les donné qu'on recoit au fur et a mesure on doit faire de copy inutile pour assamblé les morceaux pour parser la request.
et si on envoie les donnés quand on a une requette complet on doit la parsé partielement dans le module net pour savoir que la requet est fini donc pourquoi en l'envoie via std::vector<std::byte> et pas dans un forme deja parser
de plus pourquoi ne pas passer le std::vector<std::byte> dans le callback par rvalue reference pour transfere l'ownership et evite une copy

**Comment by scorsi** [comment]
Hello,

Je t'invite à regarder ma réponse de #26.

Est-ce que ça réponds à tes questions ?

**Comment by Ralender** [comment]
merci de ta reponse.
dommage que les créateurs de l'api ne repond pas...
