### ISSUE TITLE
Module Network: Send, Run, NetInfo

### ISSUE THREAD

**Issue by AEnguerrand** [kiwixz/sza#26]
Bonjour,

Je suis en train d'implémenter le module network demandé par l'API.

A quoi servent les fonctions `run` et `send` dans le process d'une requête ?
Je suppose que `run` va attendre un event network, puis call le `callback` qui va lancer depuis le Zia Core les autres modules et qui, une fois que tout est fini, va call `send`.

Dans ce cas, pourquoi envoyer `ImplSocket ` qu'on ne peut pas utiliser hors du module Network ?

Serait-il possible d'avoir de la documentation sur le process entre les fonctions d'API et un diagramme de séquence ?

Quel est le but réel du module network et ses interactions avec le Zia Core ?

Merci d'avance.

cc @MickaToast

**Comment by scorsi** [comment]
Hello,

Comme les gars responsables de l'API sont en vacances... Je vais essayer de répondre au mieux à tes questions.

En fait, le serveur Zia ne possède qu'un seul "module" Network dans la pipeline. `run` permet simplement de lancer le network et de le mettre en attente de connexion. `send` permet d'envoyer les données grâce au raw data se trouvant dans l'HttpDuplex de la pipeline.

Le `callback` permet au network de prévenir le core d'une requête.

En gros, dans le network tu as une espèce de select et lorsque tu reçois une requête tu appelles le callback pour prévenir de la requête et tu continues le select. 

Ensuite c'est au core de prendre la requête, la parser, former une pre-reponse en fonction de la requête puis d'appeler les modules les uns après les autres pour finir appeler la fonction `send` une fois que le processus est finit. 

`ImplSocket`, c'est une grosse merde mal pensée inutilisable. Sur Lille, nous sommes partis pour tous utiliser une implementation basique de ce truc pour pouvoir au moins s'en servir. 

Dans notre surcharge (https://github.com/scorsi/SZA-plus-plus) nous prévoyons de définir ce truc à une interface encapsulant un possible `send` et `receive` permettant à des modules de faire des requêtes réseaux comme pour le module SSL. Je t'invite à l'utiliser si tu le souhaites, elle est mieux pensée que l'API de base et est compliant. Elle n'es pas finit mais la surcharge du net arrive cette semaine. 

En espérant avoir répondu à tes questions,

**Comment by kiwixz** [comment]
@AEnguerrand 
Ta supposition est correcte. ImplSocket permet juste au module Net de savoir sur quel socket répondre. Elle pourrait ne contenir que le fd, ou un pointeur, mais si le module souhaite y stocker autre chose (pour le keep-alive par exemple), libre à lui.
Nous sommes en train de voir ce que l'on peut faire pour le diagramme de séquence.
Le module Net (dans lequel SSL doit, si besoin, être implémenté) gère **tout** ce qui est relatif au réseau, et ces interactions sont exactement celle que tu as décrites.
