### ISSUE TITLE
Stockage des paramètres

### ISSUE THREAD

**Issue by ArnaudWurmel** [kiwixz/sza#27]
Hello,

Par rapport aux paramètres des requêtes représentés par HttpDuplex.

Si j'ai bien compris, chaque module doit, s'il y en a la nécessité re-parser la string "uri" ou encore le body pour récupérer les paramètres de la requête. Ne serait-ce pas mieux de laisser ce travail au module Http ? Et donc de stocké ce résultat dans une map clé/valeur (string:string pour les paramètres GET et string:Raw pour le body).

Sinon, confirmez-vous que le module qui utilise ces paramètres doit parser les données bruts d'abord ?

**Comment by kiwixz** [comment]
Si par paramètres tu entends headers, il sont parsés au préalable et stockés dans la variables éponyme.
Si par paramètres tu parles des arguments contenu dans l'URL après le '?' pour les GET alors effectivement chaque module est autonome.

**Comment by ArnaudWurmel** [comment]
Ok, ma question était orientée par rapport à ta deuxième réponse, merci.
