### ISSUE TITLE
api::Net::send keep-alive

### ISSUE THREAD

**Issue by ArnaudWurmel** [kiwixz/sza#28]
Hello,

Est-ce possible d'envoyer le HttpDuplex& dans le send du Network.
Dans le cas où on veut gérer le keep-alive sur la socket, on a besoin des headers de la requête afin de savoir si on doit ou non fermer la socket.

Sinon, comment gérer cela ?

**Comment by scorsi** [comment]
Hello,

Malheureusement, le `send` du net ne prends en paramètre que la donnée de la réponse dans son format final (chaîne de caractères).

Si vous souhaitez gérer le Keep-Alive il faudrait faire un module en fin de pipeline qui va ping le Net pour informer que le socket doit rester ouvert.

MAIS ce n'est absolument pas complient et vous aurez des risques de Segfault car si le net n’est pas implémenté pas comme vous le souhaitez, vous ne pouvez pas le savoir étant donné que lors d'un chargement d'une lib (dll ou so) ne permet pas de connaitre l'implémentation de l'objet manipulé (les `dynamic_cast` renverront `nullptr`).

En espérant avoir répondu à ta question.

PS: Tu peux trouver une surcharge de la lib plus poussé ici (et avec un vrai support) : https://github.com/scorsi/SZA-plus-plus.

Sylvain

**Comment by ArnaudWurmel** [comment]
C'est pour cela que je demandais une légère mise à jour de l'api.

Je doute qu'utiliser une autre API soit la solution.

**Comment by scorsi** [comment]
L'API ne changera pas. Déjà qu'ils ne répondent pas aux issues.

Ce n'est pas une autre API mais une surcharge complient qui aide à la mise en place des modules, réponses, requêtes et configurations. Autorisé par l'ADM Lille et responsable du module. A toi de voir.

**Comment by kiwixz** [comment]
Cette question à déjà été traitée dans #21 .
