### ISSUE TITLE
Paramètres des requêtes POST et PUT

### ISSUE THREAD

**Issue by My42** [kiwixz/sza#29]
Bonsoir,

Comment pouvons nous stocker les paramètres d'une requête POST ou PUT ? Car pour l'instant, à part si je me trompe, il va falloir parser _body_ présent dans la structure _HttpRequest_ à chaque fois que l'on a besoin de ces derniers.

Pourquoi n'y a t'il pas une `std::map<std::string, std::string>`  comme pour les paramètres du header ?

**Comment by ArnaudWurmel** [comment]
Les paramètres POST peuvent être juste sous forme de row ou encore JSON, il n'y a pas de moyen de définir un format constant sous la forme string: string.

**Comment by kiwixz** [comment]
En effet, comme précisé par @ArnaudWurmel, la forme de ces paramètres varient trop pour être facilement stockable. Nous n'avons pas trouvé de moyen satisfaisant pour répondre à ce problème, qui n'est qu'un soucis d'optimisation.
Donc effectivement, comme pour l'issue #27, chaque module est autonome.
