### ISSUE TITLE
Respect rfc2324

### ISSUE THREAD

**Issue by Xephi** [kiwixz/sza#3]
Hello !

Your api seems to do not follow the rfc2324 correctly : 
https://www.ietf.org/rfc/rfc2324.txt

Can you please do a fix to handle the HTCPCP/1.0 Protocol ?

**Comment by Xephi** [comment]
Even Google follows this rfc:
https://www.google.com/teapot

I'll do a pull request tomorrow if it's still unfixed :P

**Comment by kiwixz** [comment]
Feature added in commit 609573820e7a82d349374dcad2db7c4a465921a9 !

**Comment by Xephi** [comment]
Thanks for this very important fix!
