### ISSUE TITLE
std::vector + Net class copy in call back

### ISSUE THREAD

**Issue by polosskevin** [kiwixz/sza#5]
Same as issue #4 
Why do we have a copy here ?
```c++
using Callback = std::function<void(Raw, NetInfo)>;
```
possible fix:
```c++
using Callback = std::function<void(Raw &, NetInfo const &)>;
```
```c++
using Callback = std::function<void(Raw const &, NetInfo const &)>;
```

**Comment by kiwixz** [comment]
The callback is expected to create a `HttpDuplex` struct, so a copy has to be done. Furthermore, it really seems more coherent for the callback to own this data.

**Comment by polosskevin** [comment]
The copy can be done in the call back. Here if you create a httpduplex inside the call back there will be 2 copy, the first one when you pass it as parameter and when you store it. But if you pass it as const reference and do a copy there will be only one.
But i do agree with the last point.

**Comment by kiwixz** [comment]
The second "copy" could just be a move, so there is only one copy.

**Comment by polosskevin** [comment]
Yes
