### ISSUE TITLE
RFC non compliant

### ISSUE THREAD

**Issue by polosskevin** [kiwixz/sza#6]
Is it possible to have an api that respect the correct RFC please ?
In fact the code status of an http response can be user define. As proposed the http status is only a enum class and as a result can't satisfy this RFC rule.
```c++
enum class Status {...}
```
possible fix
```c++
enum Status {...}
```

**Comment by scorsi** [comment]
To be sure `int` is used, you can type as follow:
```cpp
enum Status : int { ... }
```

**Comment by kiwixz** [comment]
Fixed.
