### ISSUE TITLE
raw pointer

### ISSUE THREAD

**Issue by polosskevin** [kiwixz/sza#7]
I don't understand why you can't have a smart pointer for the socket impl is there any particular reason ?
```c++
    /**
    * Infos on client.
    */
    struct NetInfo {
        std::chrono::system_clock::time_point time;
        std::chrono::steady_clock::time_point start;

        NetIp         ip;
        std::uint16_t port;

        ImplSocket* sock;
    };
```

**Comment by marinij** [comment]
As said before, undefined behavior can occur when you have an incomplete type and you call `delete` on it.  
So the implementation must take care of deleting the `ImplSocket* sock`, as we don't know if it was implemented or not.

More infos: [](http://howardhinnant.github.io/incomplete.html)

**Comment by scorsi** [comment]
Tell me if I'm wrong but, when I read your article, I understand that using `delete` (so raw pointer) on imcomplete type may occure undefined behaviour (same for `std::auto_ptr`) but this is not the case for `std::unique_ptr` and for `std::shared_ptr`.
```
Undefined behavior can occur when you have an incomplete type and you call delete on it: 
class A;
A* a = ...;
delete a;
[...]
Using auto_ptr<A> in the above example doesn't help.
You still get the same undefined behavior as if you had used a raw pointer. 
[...]
Nevertheless, using incomplete classes in certain places is very useful!
This is where shared_ptr and unique_ptr help.
[...]
No more undefined behavior: 
If your code compiles, then you've used a complete type everywhere you need to. 
class A
{
    class impl;
    std::unique_ptr<impl> ptr_;  // ok!

public:
    A();
    ~A();
    // ...
};
```

**Comment by marinij** [comment]
Yes, but then it won't compile until the implementation of `ImplSocket` is done.

**Comment by scorsi** [comment]
Yes this is the point accentuated in the #8.

**Comment by polosskevin** [comment]
You can specify a custom deleter to smart pointer. So as it is a pointer why not doing something like this:
```c++
using sokectImpl = std::any;
std::shared_ptr<sokectImpl> socketImpl;
```

**Comment by scorsi** [comment]
I'm not sure this is a good idea. This mean that socketImpl is now a anything which is now great at all, because we don't know what is behind the variable.

I suggest to stay at the #8 issue which will unlock this one I think.

**Comment by polosskevin** [comment]
It is a row pointer it is already anything.

**Comment by scorsi** [comment]
Not exactly, but your solution still better than the actual purpose.
I think when the #8 will be fixed and closed, this issue will be too. :)

**Comment by PierreBougon** [comment]
You can't make a prohibithed because of a bad implementation of the variable. In modern cpp, if you're not writing a container or writing a C specific code you should never ever use C ptr. In fact here issue #8 must be fix and you will can fix this one.

**Comment by kiwixz** [comment]
As #8 is resolved, I close this one.
