### ISSUE TITLE
ImplSocket

### ISSUE THREAD

**Issue by scorsi** [kiwixz/sza#8]
Hi,

As `ImplSocket` is forward declared. How can we know how to use it ?
How module can properly use this struct in differents Zia implementation ?

**Comment by marinij** [comment]
The `ImplSocket` implementation is totally free, so there is neither good nor bad way of using it, as long as it does the job of a socket, that you'll use in your `Net` subclass.

**Comment by scorsi** [comment]
Ok, but how module can use this struct in differents Zia implementation if it don't know what is it ?
Because every module must work properly in every different Zia implementation.

**Comment by polosskevin** [comment]
So how the ssl module is going to handle a particular way to read on the socket ?

**Comment by marinij** [comment]
@scorsi Only your 'Network' module implements and uses the `struct ImplSocket`, so he does know how to use it.

@polosskevin Our idea is that you have to implement together all the modules that need access to the `struct ImplSocket`, so if your SSL module requires to read/write on the socket, merge it with your Network one.

**Comment by scorsi** [comment]
The `HttpDuplex` has a `NetInfo` and in the `NetInfo` we found the `ImplSocket`. 
So modules (by `exec` method) got this `ImplSocket` as parameter.
The problem's still here.

"if your SSL module requires to read/write on the socket, merge it with your Network one"
We should so put the SLL into the Zia itself ? SSL must be a module.

**Comment by marinij** [comment]
`HttpDuplex::NetInfo::ImplSocket` is only useful in your Network module, which has the `struct ImplSocket` implemented. This attribute is not required for any other modules.

As I said before, if your SSL module requires to read/write on the socket, you need to merge it with all the modules that requires that access and create a 'Network' module, that uses your `Net` subclass and your `struct ImplSocket`.

**Comment by scorsi** [comment]
Ok, so you have to create a module "Network". This is still a module so it is not compiled/packaged with the Zia HTTPd, and so it didn't know the `ImplSocket` implementation.

**Comment by kiwixz** [comment]
As mentioned on Yammer, the Network module is a special one and not part of "the module pipeline" for request processing. It, and only it, knows about `ImplSocket`.

**Comment by scorsi** [comment]
Yes I understand but the SSL Module must be a module and not a part of the Zia HTTPd. This is mandatory in the subject.
```
No matter what API is elected, each group MUST provide two mandatory modules for the
final defense: the secure connection module and the PHP CGI module.
```

**Comment by kiwixz** [comment]
What's the problem then ?

**Comment by scorsi** [comment]
I'm so lost. 
You said that the Network module is a module which knows the ImplSocket implementation. What does do this module? What does the Zia HTTPd if it can't mastery the Network part? Zia HTTPd should work without modules. 
@marinij said that the SSL Module must be in the Network Module, you seem to not be agree with him...

**Comment by PierreBougon** [comment]
`ImplSocket` is a part of `NetInfo`
```cpp
    /**
    * Struct identifying socket (implementation-defined).
    */
    struct ImplSocket;

    /**
    * Infos on client.
    */
    struct NetInfo {
        std::chrono::system_clock::time_point time;
        std::chrono::steady_clock::time_point start;

        NetIp         ip;
        std::uint16_t port;

        ImplSocket* sock;
    };
```

and `NetInfo` is a part of ``HttpDuplex`

```cpp
    /**
    * Represents all data concerning a request and its response during pipeline processing.
    */
    struct HttpDuplex {
        NetInfo      info;
        Net::Raw     raw_req;
        Net::Raw     raw_resp;
        HttpRequest  req;
        HttpResponse resp;
    };
```

which is passed to all modules in the exec method :

```cpp
        /**
        * Called on HTTP request.
        * \return true on success, otherwise false.
        */
        virtual bool exec(HttpDuplex& http) = 0;
```

How can we implement a module without the implementation of a data passed in parameter ? Should we ignore it ? I dont want to have useless data in my module. Network is a special module in your implementation you should prepare a way to do a special module.

**Comment by scorsi** [comment]
@PierreBougon, I already said that but they said:
```HttpDuplex::NetInfo::ImplSocket is only useful in your Network module, which has the struct ImplSocket implemented. This attribute is not required for any other modules.```

**Comment by PierreBougon** [comment]
@scorsi Yes they said that. And I still don't want to have Network non implemented data structure in my module because *it won't be possible to make module*. How can a module know the implementation of `ImplSocket` ? It can't because it is not implemented. So I cannot do a simple module. It's an obvious error.

Each group will have its own implementation of this struct > multiple declarations / differents declarations.

**Comment by scorsi** [comment]
I am totally agreed with you

**Comment by MarcBrout** [comment]
You can't have structures that are implementation **dependant** and modules that can use that said structure and also be **interchangeable** through all Zia different implementations. Modules being interchangeable  is a subject requirement.

**Comment by scorsi** [comment]
Instead of require a Socket implementation, why not using this :
```cpp
class NetworkCommunication {
     public bool sendDataToClient(const Net::Raw &data) = 0;
     public const Net::Raw receiveDataToClient() = 0; // Return a copy here
}
```
And pass this interface to modules, so they can comunicate with the Zia without knowing the socket implementation.

**Comment by kiwixz** [comment]
You totally miss the point. The structure is implementation defined, but only used in implementation.
Other modules are not dependent of the Network "module", as they are not supposed to understand `ImplSocket` structure, they just pass it around so they can send back data to client.

Modules are interchangeable, because they do not know what `ImplSocket` is, so they are not dependent on it.

**Comment by kiwixz** [comment]
@PierreBougon Network "module" must implement class `Net` while pipeline modules implement `Module`.

**Comment by PierreBougon** [comment]
@kiwixz  Please read my answer once again. I can't have a module which can access a data undifined.

**Comment by scorsi** [comment]
Do you try to compile a module ? This is not working. Why ? Because if you type somewhere a undefined struct, compiler will say "Wtf are u doing here?" this is absollutly normal. I can't tell you "Hey Vector is here", you should probably say "Who is Vector?", the compiler works the same.

**Comment by kiwixz** [comment]
This is only a pointer, and we do not use it in another modules, so the compiler has no reason to ask for the `ImplSocket` definition.

Did you try it ? Can you actually give me some example of failure I can work with ?

**Comment by scorsi** [comment]
Since I don't understand how this API works I can't create any module... But Im trying.

**Comment by scorsi** [comment]
Why did you close that issue ? I think that this isn't the end.
I create this module:
```cpp
class Test : zia::api::Module {
private:
    zia::api::Conf conf;
public:
    Test() = default;

    ~Test() override = default;

    bool config(const zia::api::Conf &conf) override {
        this->conf = conf;
    }

    bool exec(zia::api::HttpDuplex &http) override {
        http.resp.body.clear();
        for (const auto &item: "test") {
            http.resp.body.push_back(std::byte{static_cast<std::byte>(item)});
        }
        return true;
    }
};
```
And it compiles, you were right.

There's one thing I want to know so, but I will create a new issue for.
